### ISSUE TITLE
may you recommend something similar but in python?

### ISSUE THREAD

**Issue by Sandy4321** [RAPLER/dst-1#1]
may you recommend something similar but in python?
by the way what is best book to read about DS for very beginner?

**Comment by RAPLER** [comment]
Hello,

I don't program in Python, so I cannot give any advice, but here is a
Python implementation of Dempster-Shafer Theory:

https://pypi.org/project/py_dempster_shafer/

As for the best book for the very beginner, this is a difficult question.

There are  many publicationsn on the Web on the subject of Dempster-Shafer
Theory, but not many books. I would suggest the first three chapters of
Glenn Shafer's original book "A Mathematical Theory of Evidence" (about 75
pages).

We can certainly find some primers on the Web, such as:

http://what-when-how.com/artificial-intelligence/the-dempster-shafer-theory-artificial-intelligence/

or a video presentation
https://www.youtube.com/watch?v=4rB8t6yvXIA

Hope this helps.

Regards,

Claude

Le ven. 15 févr. 2019 à 11:17, Sandy4321 <notifications@github.com> a
écrit :
