### ISSUE TITLE
Feature request: calculate bel_plau for selected subsets

### ISSUE THREAD

**Issue by garyzhubc** [RAPLER/dst-1#16]
For a bca that has 23178 subsets, it takes way too long to compute bel_plau for every subset. If I'm only interested in bel_plau for a few given subsets, what functions shall I use to efficiently retrieve bel_plau from this bca?

**Comment by garyzhubc** [comment]
I'm interested in making this enhancement myself. Seems to be an easy function to make. The main function seems like whether a bca$tt[I,] subset is a subset of a some given sets.

**Comment by garyzhubc** [comment]
```
calc_bel_plau <-function(bpa, tt_) {
  bel <- rep(0,nrow(tt_))
  disbel <- rep(0,nrow(tt_))
  for (i in 1:nrow(bpa$tt)) {
    print(i)
    for (j in 1:nrow(tt_)) {
      # if bpa$tt[i,] is contained in tt_[j,]
      if (all(tt_[j,]-bpa$tt[i,] >= 0)) {
        bel[j] <- bel[j] + bpa$spec[i,2]
      }
      # if complement of bpa$tt[i,] is contained in tt_[j,]
      if (all(+(!tt_[j,])-bpa$tt[i,] >= 0)) {
        disbel[j] <- disbel[j] + bpa$spec[i,2]
      }
    }
    # if (i == 100) break
  }
  plau <- 1 - disbel
  return(cbind(bel,plau))
}
```

This is the code that I just came up with. Could you comment on the efficiency of this computation with your design philosophy?

**Comment by garyzhubc** [comment]
This still takes a huge time to compute. Not sure if array operations, like you're using in belplau, can speed this up.

**Comment by RAPLER** [comment]
I'll try to take a look at your function tomorrow.

Le lun. 2 oct. 2023 à 17:08, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by RAPLER** [comment]
Can you explain your second input parameter (tt_).

**Comment by garyzhubc** [comment]
They are hypotheses to be tested, same format as bpa$tt.

**Comment by RAPLER** [comment]
This is a nice program. Was about three times faster than actual function "belplau" on yhe dataset I used to check. Good idea to compute plausibility using the equation 1-bel(complement).  The array operations in "belplau" are time consuming, namely the use of function "dotprod".

**Comment by garyzhubc** [comment]
Perfect. I’ll make a pull request later. I’m sure this can be further optimized by using only one check only but this likely wouldn’t be a big computational advantage. Also this can be parallelized.Sent from my iPhoneOn Oct 7, 2023, at 6:04 PM, Claude Boivin ***@***.***> wrote:﻿
Thisis a nice program. Was about three times faster than actual function "belplau" on yhe dataset I used to check. Good idea to compute plausibility using the equation 1-bel(complement).  The array operations in "belplau" are time consuming, namely the use of function "dotprod".
