### ISSUE TITLE
Put Section 3.6 of dsrwon in ttmatrix function

### ISSUE THREAD

**Issue by RAPLER** [RAPLER/dst-1#36]
"call ttmatirx with an option of using sparse matrix, replacing (not) skpt_tt"
- add parameter to ttmatrix: sparse = c("yes", "no")

1. Actual code for sparse = "no"
2. Code from dsrwon, section 3.6 for sparse = "yes"
3.  replace lines 291-314 of dsrwon by
`tt <- ttmatrix(W1s, sparse = "yes")`

**Comment by garyzhubc** [comment]
Could you explain a bit more about the rationale behind line 291-314 of dsrwon? Maybe that will help me with loading the sparse matrix index.

**Comment by garyzhubc** [comment]
Or, if it's not a direct copy from dsrwon, maybe it's better to pass bca directly to ttmatrix because other information such as varnames would be useful as elements of the frame must be put in the same order as the original bca if this ttmatrix is going to be fed into that bca.

**Comment by garyzhubc** [comment]
I have already coded a ttmatrix with sparse option. Can it substitute the lines in dsrwon?

**Comment by garyzhubc** [comment]
Right now it cannot handle "Emptyset". What operations are expected for "Emptyset"? How is it stored in sparseMatrix?

**Comment by RAPLER** [comment]
I would prefer pass only the ssnames list to keep the function lighter. I have done the same with its receprocal (DoSSnames).

I used to always put the frame as the last string of the ssnames list. So you can use this feature to set the valuenames and avoid the check for valuenames.

Seems that you don't find the empty set in this code of yours
 for(i in ifelse(length(x[[1]]) == 1, ifelse(x[[1]] == "Empty", 2, 1), 1):length(x)) {
      rowIdx<-c(rowIdx,rep(i,length(x[[i]])))
      colId <- match(x[[i]],valuenames)
      colIdx<-c(colIdx,colId)
    }
This code from should work:
# determine the column indices of each subset
# these two lines find the indices of each subset. 
# If there is no indice (empty set), it will return integer(0).
    zframe <- x[[length(x)]]
    zz1 <- lapply(X=1:length(x), FUN= function(X) {lapply(X=1:length(x[[X]]), FUN = function(Y) {which(zframe == (x[[X]])[Y])}) } )
    #
    # construct the corresponding sparse tt matrix of the resulting subset names
    rowIdx <- vector()
    colIdx <- vector()
    for (i in 1:length(x) )  {
      tempc <-  (unlist(zz1[[i]]) )
      colIdx <- c(colIdx, tempc )
      tempr <- rep(i,sum(tempc >0) )
      rowIdx <- c(rowIdx, tempr)
    }
    # Obtain sparse tt matrix of the result
    tt <- Matrix::sparseMatrix(
      i = rowIdx,
      j = colIdx, 
      x = 1, 
      dims = c(length(x), length(zframe) )
    )
    colnames(tt) <- zframe
    rownames(tt) <- nameRows(tt)

**Comment by garyzhubc** [comment]
I'm not sure what you mean by "Seems that you don't find the empty set in
this code of yours"?

Will this code work if "Empty" is the first element? Maybe you cannot put
"Empty" as the first row of the sparse matrix? So instead would you skip
the first row? That's what I've done.

**Comment by garyzhubc** [comment]
Also, is the whole frame always going to be there? What if you assign mass
one to a subset of a frame, and that frame has no masses assigned anymore?

**Comment by RAPLER** [comment]
I was referring to your for if else line of code. If you look at the lines of code in section 3.6 of dsrwon, you’ll see that it serves to identify indices for each subset, including the empty one.  Just replace the W1 input by your list of subsets, including the frame as the last one.And yes, the frame must always be there.C. B.Le 8 déc. 2023 à 22:14, Peiyuan Zhu ***@***.***> a écrit :yes﻿Also, is the whole frame always going to be there? What if you assign mass

one to a subset of a frame, and that frame has no masses assigned anymore?

**Comment by garyzhubc** [comment]
I see. Just wondering: is my version still correct, just not as elegant?Sent from my iPhoneOn Dec 9, 2023, at 6:54 AM, Claude Boivin ***@***.***> wrote:﻿
I was referring to your for if else line of code. If you look at the lines of code in section 3.6 of dsrwon, you’ll see that it serves to identify indices for each subset, including the empty one.  Just replace the W1 input by your list of subsets, including the frame as the last one.And yes, the frame must always be there.C. B.Le 8 déc. 2023 à 22:14, Peiyuan Zhu ***@***.***> a écrit :yes﻿Also, is the whole frame always going to be there? What if you assign mass



one to a subset of a frame, and that frame has no masses assigned anymore?

**Comment by RAPLER** [comment]
I am sure you can do something more elegant and correct. For my part, I
tend to stop working when I find something that works:)

Le sam. 9 déc. 2023 à 11:14, Peiyuan Zhu ***@***.***> a
écrit :

> I see. Just wondering: is my version still correct, just not as
> elegant?Sent from my iPhoneOn Dec 9, 2023, at 6:54 AM, Claude Boivin
> ***@***.***> wrote:﻿
> I was referring to your for if else line of code. If you look at the lines
> of code in section 3.6 of dsrwon, you’ll see that it serves to identify
> indices for each subset, including the empty one.  Just replace the W1
> input by your list of subsets, including the frame as the last one.And yes,
> the frame must always be there.C. B.Le 8 déc. 2023 à 22:14, Peiyuan Zhu
> ***@***.***> a écrit :yes﻿Also, is the whole frame always going to be
> there? What if you assign mass
>
>
>
> one to a subset of a frame, and that frame has no masses assigned anymore?
>
>
>
>
>
>
>

**Comment by garyzhubc** [comment]
I added a checker in nzdsr for sparse option. Is this necessary?

**Comment by RAPLER** [comment]
Does Not appear  to be necessary. The result is the same.

Le lun. 11 déc. 2023 à 13:10, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment]
There may be a need to load ttmatrix. In case it is loaded in nzdsr the sparse version is much faster.

**Comment by RAPLER** [comment]
tt matrix function seems to work well. In dsrwon, I have replaced the code lines 299 to 320 by a call to ttmatrix.

**Comment by RAPLER** [comment]
Issue closed
