### ISSUE TITLE
Succinct product space representation

### ISSUE THREAD

**Issue by garyzhubc** [RAPLER/dst-1#39]
It seems that often times the combinations are done on product spaces with little need to enumerate all combinations of elements. Is there a more succinct representation of the belief assignment like it is done in this paper https://www.stat.purdue.edu/~chuanhai/projects/DS/docs/IJIS2006.pdf?

**Comment by garyzhubc** [comment]
It seems like “partitions” are better abstractions than “variables”. This will be especially important in high-dimensional data analysis because giving probabilities to partitions will be much easier than giving probabilities to individual variables.

**Comment by RAPLER** [comment]
I am looking into the paper of Dempster and Wai Fung Chiu. So far, I have not been able to do their simple example with K=1 and N =1.

Can you be more precise about what you intend by "partitions"? In this paper, they seems to consider each row of a dataset of size N+1 as objects with K binary variables, giving a full graph of (N+1) x K variables.

**Comment by garyzhubc** [comment]
I think you're right. This isn't a good idea.
