### ISSUE TITLE
 No method or default for coercing “matrix” to “RsparseMatrix”

### ISSUE THREAD

**Issue by garyzhubc** [RAPLER/dst-1#41]
at times I run into this type of error:
```
Error in methods::as(bma$tt, "RsparseMatrix") : 
  no method or default for coercing “matrix” to “RsparseMatrix”
Execution halted
```

**Comment by RAPLER** [comment]
Can you tell me in which function this occurs?

**Comment by garyzhubc** [comment]
It was when I'm converting regular matrix into sparse matrix
```
bma$tt <- methods::as(bma$tt, "RsparseMatrix")
```

**Comment by RAPLER** [comment]
In which function of the package?


C. B.

**Comment by garyzhubc** [comment]
It’s not part of the package, but an issue that I have in converting sparse matrix as required by the package. Sent from my iPhoneOn Mar 14, 2024, at 2:28 PM, Claude Boivin ***@***.***> wrote:﻿
In which function of the package?





C. B.

**Comment by RAPLER** [comment]
I have already run into this problem, although it was within the package. I solved this by adding the package "methods" in the imports of the DESCRIPTION file. If the problem arise in a function you have defined, you may need to add:
 @import methods
see this page on stackoverflow website:
https://stackoverflow.com/questions/36432248/error-in-asdata-transactions-no-method-or-default-for-coercing-data-to
