### ISSUE TITLE
Empty set among the focal elements. Normalization necessary. See nzdsr function.

### ISSUE THREAD

**Issue by garyzhubc** [RAPLER/dst-1#5]
What does this error mean?
```
> bel_bpa <- belplau(bpa)
Error in belplau(bpa) : 
  Invalid data: Empty set among the focal elements. Normalization necessary. See nzdsr function.
```

**Comment by RAPLER** [comment]
Hi,
The error message means that some of the intersections of subsets give the
empty set as a result. This is to be expected when you apply Dempster's
rule of combination to a great number of distinct subsets. Inevitably, some
results will be contradictory. When this is the case, we recalculate the
mass values  obtained  by dividing the mass value of the non-empty subsets
by 1 minus the mass of the empty set. This is what the function "nzdsr" do.
Function "belplau" can be used on results which do not contain a non-zero
mass allocated to the empty set.

Regards,

Claude

Le jeu. 29 déc. 2022 à 11:16, Peiyuan Zhu ***@***.***> a
écrit :
