### ISSUE TITLE
Feature request: numerical stability & sparse representation

### ISSUE THREAD

**Issue by garyzhubc** [RAPLER/dst-1#9]
~~Use of logarithm in combination rule to increase numerical stability: logsumexp~~

~~Use of sparse matrix in bca representation to reduce space complexity: transpose, dotprod~~

Catching error when numerical instability occur.

**Comment by garyzhubc** [comment]
Reopen this. Still don't know whether R has numerical stability issue when multiplying a large number of small numbers 1e-5.

**Comment by garyzhubc** [comment]
Added Logsumexp so one can compare a more numerically robust version with the original version.

**Comment by garyzhubc** [comment]
So far all the logsumexp versions of initial implementations have no experienced issue. Is it good time to replace the initial implementations?

**Comment by RAPLER** [comment]
Hi Gary,

I have done a check package run (devtools::check(document = FALSE) ). It
didn't pass. Maybe these errors are not related to the new logsumexp
versions. Nevertheless, I suggest clearing the errors before replacing old
functions with new ones and checking the package again, just to make
certain we don't have too many bugs to chase at the same time.

3 errors ✖ | 1 warning ✖ |

2 notes ✖

Error: R CMD check found ERRORs
Execution halted

Best regards,

Claude


Le ven. 8 déc. 2023 à 00:37, Peiyuan Zhu ***@***.***> a
écrit :
